version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: config/docker/Dockerfile.backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
    depends_on:
      - mongodb
      - redis

  frontend:
    build:
      context: .
      dockerfile: config/docker/Dockerfile.frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app

  mongodb:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  mongodb_data:
